In [2]:
from dotenv import load_dotenv

load_dotenv()

True

In [15]:

import pandas as pd


filename = "2_pm_BTC_1h.csv"

pm_df = pd.read_csv(
    f"../data/{filename}", parse_dates=["Date (UTC)"], index_col="Date (UTC)"
)
pm_df.head()

,Timestamp (UTC),"$200,000","$150,000","$140,000","$130,000","$120,000","$110,000","$105,000","$100,000","$90,000","$85,000","$80,000","$70,000","$60,000","$50,000"
Date (UTC),,,,,,,,,,,,,,,
2025-01-02 20:00:00,1735848003,0.0250,0.0700,0.0700,0.16,0.390,0.475,0.790,0.840,0.450,0.130,0.25,0.095,0.1000,0.0800
2025-01-02 21:00:00,1735851603,0.0320,0.0300,0.0400,0.10,0.305,0.465,0.640,0.840,0.590,0.190,0.25,0.090,0.0900,0.0550
2025-01-02 22:00:00,1735855203,0.0275,0.0300,0.0395,0.09,0.210,0.415,0.585,0.845,0.595,0.380,0.28,0.090,0.0900,0.0350
2025-01-02 23:00:00,1735858804,0.0125,0.0295,0.0390,0.07,0.150,0.390,0.580,0.845,0.590,0.365,0.25,0.095,0.0350,0.0125
2025-01-03 00:00:00,1735862404,0.0125,0.0275,0.0390,0.07,0.165,0.395,0.580,0.850,0.590,0.395,0.24,0.065,0.0255,0.0125

In [ ]:
bet_cols = pm_df.columns[pm_df.columns.str.startswith("$")]

new_bet_cols = [col.split(",")[0].split("$")[1] for col in bet_cols]

rename_mapping = {f"${col},000": col for col in new_bet_cols}
pm_df = pm_df.rename(columns=rename_mapping)
pm_df.head()

,Timestamp (UTC),200,150,140,130,120,110,105,100,90,85,80,70,60,50
Date (UTC),,,,,,,,,,,,,,,
2025-01-02 20:00:00,1735848003,0.0250,0.0700,0.0700,0.16,0.390,0.475,0.790,0.840,0.450,0.130,0.25,0.095,0.1000,0.0800
2025-01-02 21:00:00,1735851603,0.0320,0.0300,0.0400,0.10,0.305,0.465,0.640,0.840,0.590,0.190,0.25,0.090,0.0900,0.0550
2025-01-02 22:00:00,1735855203,0.0275,0.0300,0.0395,0.09,0.210,0.415,0.585,0.845,0.595,0.380,0.28,0.090,0.0900,0.0350
2025-01-02 23:00:00,1735858804,0.0125,0.0295,0.0390,0.07,0.150,0.390,0.580,0.845,0.590,0.365,0.25,0.095,0.0350,0.0125
2025-01-03 00:00:00,1735862404,0.0125,0.0275,0.0390,0.07,0.165,0.395,0.580,0.850,0.590,0.395,0.24,0.065,0.0255,0.0125

In [41]:
col = "80"
non_nan_idxs = pm_df[col].dropna().index
non_nan_idxs[0:5]

DatetimeIndex(['2025-01-02 20:00:00', '2025-01-02 21:00:00',
               '2025-01-02 22:00:00', '2025-01-02 23:00:00',
               '2025-01-03 00:00:00'],
              dtype='datetime64[ns]', name='Date (UTC)', freq=None)

In [42]:
start = non_nan_idxs.min()
end = non_nan_idxs[-1]
start, end

(Timestamp('2025-01-02 20:00:00'), Timestamp('2025-02-01 07:00:00'))

In [43]:
open_data = pm_df[col][start:end]
open_data.head()

Date (UTC)
2025-01-02 20:00:00    0.25
2025-01-02 21:00:00    0.25
2025-01-02 22:00:00    0.28
2025-01-02 23:00:00    0.25
2025-01-03 00:00:00    0.24
Name: 80, dtype: float64

In [ ]:
close_data = open_data.shift(-1)
delta_data = close_data - open_data
open_data[:-1].tail(), close_data[:-1].tail(), delta_data[:-1].tail()

(Date (UTC)
 2025-02-01 02:00:00    0.0010
 2025-02-01 03:00:00    0.0010
 2025-02-01 04:00:00    0.0005
 2025-02-01 05:00:00    0.0005
 2025-02-01 06:00:00    0.0005
 Name: 80, dtype: float64,
 Date (UTC)
 2025-02-01 02:00:00    0.0010
 2025-02-01 03:00:00    0.0005
 2025-02-01 04:00:00    0.0005
 2025-02-01 05:00:00    0.0005
 2025-02-01 06:00:00    0.0005
 Name: 80, dtype: float64,
 Date (UTC)
 2025-02-01 02:00:00    0.0000
 2025-02-01 03:00:00   -0.0005
 2025-02-01 04:00:00    0.0000
 2025-02-01 05:00:00    0.0000
 2025-02-01 06:00:00    0.0000
 Name: 80, dtype: float64)

In [1]:
from polymarket_datasets import load_pm_dataset


r = load_pm_dataset("1_pm_BTC_1d.csv")
r

[PMDataset(label='150', date_from=Timestamp('2024-12-13 00:00:00'), date_to=Timestamp('2025-02-08 00:00:00'), index=DatetimeIndex(['2024-12-13', '2024-12-14', '2024-12-15', '2024-12-16',
                '2024-12-17', '2024-12-18', '2024-12-19', '2024-12-20',
                '2024-12-21', '2024-12-22', '2024-12-23', '2024-12-24',
                '2024-12-25', '2024-12-26', '2024-12-27', '2024-12-28',
                '2024-12-29', '2024-12-30', '2024-12-31', '2025-01-01',
                '2025-01-02', '2025-01-03', '2025-01-04', '2025-01-05',
                '2025-01-06', '2025-01-07', '2025-01-08', '2025-01-09',
                '2025-01-10', '2025-01-11', '2025-01-12', '2025-01-13',
                '2025-01-14', '2025-01-15', '2025-01-16', '2025-01-17',
                '2025-01-18', '2025-01-19', '2025-01-20', '2025-01-21',
                '2025-01-22', '2025-01-23', '2025-01-24', '2025-01-25',
                '2025-01-26', '2025-01-27', '2025-01-28', '2025-01-29',
                '2025-01-30', '2025-01-31', '2025-02-01', '2025-02-02',
                '2025-02-03', '2025-02-04', '2025-02-05', '2025-02-06',
                '2025-02-07'],
               dtype='datetime64[ns]', name='Date (UTC)', freq=None), open=array([0.305, 0.24 , 0.235, 0.265, 0.305, 0.33 , 0.28 , 0.235, 0.235,
        0.245, 0.22 , 0.215, 0.24 , 0.245, 0.225, 0.195, 0.205, 0.165,
        0.18 , 0.145, 0.135, 0.145, 0.145, 0.165, 0.16 , 0.19 , 0.155,
        0.14 , 0.14 , 0.145, 0.135, 0.145, 0.155, 0.165, 0.175, 0.18 ,
        0.195, 0.2  , 0.185, 0.195, 0.225, 0.175, 0.165, 0.16 , 0.145,
        0.135, 0.125, 0.105, 0.11 , 0.1  , 0.095, 0.075, 0.075, 0.09 ,
        0.075, 0.06 , 0.055]), close=array([0.24 , 0.235, 0.265, 0.305, 0.33 , 0.28 , 0.235, 0.235, 0.245,
        0.22 , 0.215, 0.24 , 0.245, 0.225, 0.195, 0.205, 0.165, 0.18 ,
        0.145, 0.135, 0.145, 0.145, 0.165, 0.16 , 0.19 , 0.155, 0.14 ,
        0.14 , 0.145, 0.135, 0.145, 0.155, 0.165, 0.175, 0.18 , 0.195,
        0.2  , 0.185, 0.195, 0.225, 0.175, 0.165, 0.16 , 0.145, 0.135,
        0.125, 0.105, 0.11 , 0.1  , 0.095, 0.075, 0.075, 0.09 , 0.075,
        0.06 , 0.055, 0.05 ]), delta=array([-0.065, -0.005,  0.03 ,  0.04 ,  0.025, -0.05 , -0.045,  0.   ,
         0.01 , -0.025, -0.005,  0.025,  0.005, -0.02 , -0.03 ,  0.01 ,
        -0.04 ,  0.015, -0.035, -0.01 ,  0.01 ,  0.   ,  0.02 , -0.005,
         0.03 , -0.035, -0.015,  0.   ,  0.005, -0.01 ,  0.01 ,  0.01 ,
         0.01 ,  0.01 ,  0.005,  0.015,  0.005, -0.015,  0.01 ,  0.03 ,
        -0.05 , -0.01 , -0.005, -0.015, -0.01 , -0.01 , -0.02 ,  0.005,
        -0.01 , -0.005, -0.02 ,  0.   ,  0.015, -0.015, -0.015, -0.005,
        -0.005])),
 PMDataset(label='120', date_from=Timestamp('2024-12-13 00:00:00'), date_to=Timestamp('2025-02-08 00:00:00'), index=DatetimeIndex(['2024-12-13', '2024-12-14', '2024-12-15', '2024-12-16',
                '2024-12-17', '2024-12-18', '2024-12-19', '2024-12-20',
                '2024-12-21', '2024-12-22', '2024-12-23', '2024-12-24',
                '2024-12-25', '2024-12-26', '2024-12-27', '2024-12-28',
                '2024-12-29', '2024-12-30', '2024-12-31', '2025-01-01',
                '2025-01-02', '2025-01-03', '2025-01-04', '2025-01-05',
                '2025-01-06', '2025-01-07', '2025-01-08', '2025-01-09',
                '2025-01-10', '2025-01-11', '2025-01-12', '2025-01-13',
                '2025-01-14', '2025-01-15', '2025-01-16', '2025-01-17',
                '2025-01-18', '2025-01-19', '2025-01-20', '2025-01-21',
                '2025-01-22', '2025-01-23', '2025-01-24', '2025-01-25',
                '2025-01-26', '2025-01-27', '2025-01-28', '2025-01-29',
                '2025-01-30', '2025-01-31', '2025-02-01', '2025-02-02',
                '2025-02-03', '2025-02-04', '2025-02-05', '2025-02-06',
                '2025-02-07'],
               dtype='datetime64[ns]', name='Date (UTC)', freq=None), open=array([0.625, 0.59 , 0.595, 0.665, 0.735, 0.7  , 0.645, 0.55 , 0.57 ,
        0.565, 0.51 , 0.51 , 0.545, 0.535, 0.495, 0.46 , 0.465, 0.45 ,
        0.43 , 0.425, 0.415, 0.475, 0.48 , 0.49 , 0.48 , 0.575, 0.48 ,
        0.465, 0.425, 0.415, 0.43 , 0.41 , 0.425, 0.43 , 0.515, 0.51 ,
        0.565, 0.61 , 0.525, 0.58 , 0.66 , 0.605, 0.615, 0.59 , 0.59 ,
        0.485, 0.49 , 0.485, 0.515, 0.53 , 0.425, 0.375, 0.365, 0.505,
        0.41 , 0.35 , 0.35 ]), close=array([0.59 , 0.595, 0.665, 0.735, 0.7  , 0.645, 0.55 , 0.57 , 0.565,
        0.51 , 0.51 , 0.545, 0.535, 0.495, 0.46 , 0.465, 0.45 , 0.43 ,
        0.425, 0.415, 0.475, 0.48 , 0.49 , 0.48 , 0.575, 0.48 , 0.465,
        0.425, 0.415, 0.43 , 0.41 , 0.425, 0.43 , 0.515, 0.51 , 0.565,
        0.61 , 0.525, 0.58 , 0.66 , 0.605, 0.615, 0.59 , 0.59 , 0.485,
        0.49 , 0.485, 0.515, 0.53 , 0.425, 0.375, 0.365, 0.505, 0.41 ,
        0.35 , 0.35 , 0.295]), delta=array([-0.035,  0.005,  0.07 ,  0.07 , -0.035, -0.055, -0.095,  0.02 ,
        -0.005, -0.055,  0.   ,  0.035, -0.01 , -0.04 , -0.035,  0.005,
        -0.015, -0.02 , -0.005, -0.01 ,  0.06 ,  0.005,  0.01 , -0.01 ,
         0.095, -0.095, -0.015, -0.04 , -0.01 ,  0.015, -0.02 ,  0.015,
         0.005,  0.085, -0.005,  0.055,  0.045, -0.085,  0.055,  0.08 ,
        -0.055,  0.01 , -0.025,  0.   , -0.105,  0.005, -0.005,  0.03 ,
         0.015, -0.105, -0.05 , -0.01 ,  0.14 , -0.095, -0.06 ,  0.   ,
        -0.055])),
 PMDataset(label='80', date_from=Timestamp('2024-12-14 00:00:00'), date_to=Timestamp('2025-02-08 00:00:00'), index=DatetimeIndex(['2024-12-14', '2024-12-15', '2024-12-16', '2024-12-17',
                '2024-12-18', '2024-12-19', '2024-12-20', '2024-12-21',
                '2024-12-22', '2024-12-23', '2024-12-24', '2024-12-25',
                '2024-12-26', '2024-12-27', '2024-12-28', '2024-12-29',
                '2024-12-30', '2024-12-31', '2025-01-01', '2025-01-02',
                '2025-01-03', '2025-01-04', '2025-01-05', '2025-01-06',
                '2025-01-07', '2025-01-08', '2025-01-09', '2025-01-10',
                '2025-01-11', '2025-01-12', '2025-01-13', '2025-01-14',
                '2025-01-15', '2025-01-16', '2025-01-17', '2025-01-18',
                '2025-01-19', '2025-01-20', '2025-01-21', '2025-01-22',
                '2025-01-23', '2025-01-24', '2025-01-25', '2025-01-26',
                '2025-01-27', '2025-01-28', '2025-01-29', '2025-01-30',
                '2025-01-31', '2025-02-01', '2025-02-02', '2025-02-03',
                '2025-02-04', '2025-02-05', '2025-02-06', '2025-02-07'],
               dtype='datetime64[ns]', name='Date (UTC)', freq=None), open=array([0.41 , 0.41 , 0.33 , 0.335, 0.32 , 0.365, 0.475, 0.435, 0.475,
        0.555, 0.555, 0.475, 0.485, 0.55 , 0.58 , 0.545, 0.58 , 0.58 ,
        0.535, 0.535, 0.485, 0.46 , 0.455, 0.44 , 0.37 , 0.415, 0.47 ,
        0.525, 0.475, 0.48 , 0.47 , 0.505, 0.465, 0.395, 0.39 , 0.325,
        0.335, 0.395, 0.375, 0.265, 0.28 , 0.255, 0.24 , 0.24 , 0.285,
        0.255, 0.25 , 0.25 , 0.215, 0.235, 0.245, 0.285, 0.215, 0.26 ,
        0.295, 0.285]), close=array([0.41 , 0.33 , 0.335, 0.32 , 0.365, 0.475, 0.435, 0.475, 0.555,
        0.555, 0.475, 0.485, 0.55 , 0.58 , 0.545, 0.58 , 0.58 , 0.535,
        0.535, 0.485, 0.46 , 0.455, 0.44 , 0.37 , 0.415, 0.47 , 0.525,
        0.475, 0.48 , 0.47 , 0.505, 0.465, 0.395, 0.39 , 0.325, 0.335,
        0.395, 0.375, 0.265, 0.28 , 0.255, 0.24 , 0.24 , 0.285, 0.255,
        0.25 , 0.25 , 0.215, 0.235, 0.245, 0.285, 0.215, 0.26 , 0.295,
        0.285, 0.29 ]), delta=array([ 0.   , -0.08 ,  0.005, -0.015,  0.045,  0.11 , -0.04 ,  0.04 ,
         0.08 ,  0.   , -0.08 ,  0.01 ,  0.065,  0.03 , -0.035,  0.035,
         0.   , -0.045,  0.   , -0.05 , -0.025, -0.005, -0.015, -0.07 ,
         0.045,  0.055,  0.055, -0.05 ,  0.005, -0.01 ,  0.035, -0.04 ,
        -0.07 , -0.005, -0.065,  0.01 ,  0.06 , -0.02 , -0.11 ,  0.015,
        -0.025, -0.015,  0.   ,  0.045, -0.03 , -0.005,  0.   , -0.035,
         0.02 ,  0.01 ,  0.04 , -0.07 ,  0.045,  0.035, -0.01 ,  0.005])),
 PMDataset(label='70', date_from=Timestamp('2024-12-14 00:00:00'), date_to=Timestamp('2025-02-08 00:00:00'), index=DatetimeIndex(['2024-12-14', '2024-12-15', '2024-12-16', '2024-12-17',
                '2024-12-18', '2024-12-19', '2024-12-20', '2024-12-21',
                '2024-12-22', '2024-12-23', '2024-12-24', '2024-12-25',
                '2024-12-26', '2024-12-27', '2024-12-28', '2024-12-29',
                '2024-12-30', '2024-12-31', '2025-01-01', '2025-01-02',
                '2025-01-03', '2025-01-04', '2025-01-05', '2025-01-06',
                '2025-01-07', '2025-01-08', '2025-01-09', '2025-01-10',
                '2025-01-11', '2025-01-12', '2025-01-13', '2025-01-14',
                '2025-01-15', '2025-01-16', '2025-01-17', '2025-01-18',
                '2025-01-19', '2025-01-20', '2025-01-21', '2025-01-22',
                '2025-01-23', '2025-01-24', '2025-01-25', '2025-01-26',
                '2025-01-27', '2025-01-28', '2025-01-29', '2025-01-30',
                '2025-01-31', '2025-02-01', '2025-02-02', '2025-02-03',
                '2025-02-04', '2025-02-05', '2025-02-06', '2025-02-07'],
               dtype='datetime64[ns]', name='Date (UTC)', freq=None), open=array([0.185, 0.245, 0.175, 0.185, 0.185, 0.245, 0.245, 0.295, 0.275,
        0.335, 0.34 , 0.28 , 0.255, 0.33 , 0.355, 0.315, 0.335, 0.37 ,
        0.32 , 0.315, 0.28 , 0.26 , 0.265, 0.275, 0.22 , 0.215, 0.23 ,
        0.255, 0.235, 0.24 , 0.235, 0.265, 0.235, 0.225, 0.22 , 0.185,
        0.185, 0.22 , 0.2  , 0.175, 0.175, 0.16 , 0.14 , 0.135, 0.135,
        0.145, 0.145, 0.12 , 0.115, 0.115, 0.105, 0.105, 0.07 , 0.09 ,
        0.085, 0.095]), close=array([0.245, 0.175, 0.185, 0.185, 0.245, 0.245, 0.295, 0.275, 0.335,
        0.34 , 0.28 , 0.255, 0.33 , 0.355, 0.315, 0.335, 0.37 , 0.32 ,
        0.315, 0.28 , 0.26 , 0.265, 0.275, 0.22 , 0.215, 0.23 , 0.255,
        0.235, 0.24 , 0.235, 0.265, 0.235, 0.225, 0.22 , 0.185, 0.185,
        0.22 , 0.2  , 0.175, 0.175, 0.16 , 0.14 , 0.135, 0.135, 0.145,
        0.145, 0.12 , 0.115, 0.115, 0.105, 0.105, 0.07 , 0.09 , 0.085,
        0.095, 0.105]), delta=array([ 0.06 , -0.07 ,  0.01 ,  0.   ,  0.06 ,  0.   ,  0.05 , -0.02 ,
         0.06 ,  0.005, -0.06 , -0.025,  0.075,  0.025, -0.04 ,  0.02 ,
         0.035, -0.05 , -0.005, -0.035, -0.02 ,  0.005,  0.01 , -0.055,
        -0.005,  0.015,  0.025, -0.02 ,  0.005, -0.005,  0.03 , -0.03 ,
        -0.01 , -0.005, -0.035,  0.   ,  0.035, -0.02 , -0.025,  0.   ,
        -0.015, -0.02 , -0.005,  0.   ,  0.01 ,  0.   , -0.025, -0.005,
         0.   , -0.01 ,  0.   , -0.035,  0.02 , -0.005,  0.01 ,  0.01 ]))]